services:
  app_react:
    build: ./front-end
    container_name: app_react
    volumes:
      - build_react:/var/www/html

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:5000
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_react

volumes:
  build_react: