services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 80:5432
    env_file:
      - .env
    volumes:
      - pg_db:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/usr/src
volumes:
  pg_db:
