name: Pull Request on Github
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out repo code
        uses: actions/checkout@v3
      - name: Creates .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "drivenops-test"
          envkey_DATABASE_URL: "postgres://postgres:postgres@db_test:5432/drivenops-test"
          file_name: .env.test
      - name: Runs tests
        run: docker-compose -f ./back-end/docker-compose-test.yml run app npm run test
      - name: Run build
        run: npm i && npm run build 